import Head from 'next/head'
import { css } from '@emotion/css';
import backgroundImage1 from '../images/background-game1.jpg'
import React from 'react';
import Desk from "../components/Desk";

export default function Game() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={css`
        background-image: url(${backgroundImage1.src});
        background-repeat: no-repeat;
        background-size: cover;
        width: 100%;
        min-height: 100vh;
        display: grid;
        place-items: center;
      `}>
        <Desk/>
        <Desk/>
      </main>
    </>
  )
}

