import Head from 'next/head'
import { css } from '@emotion/css';
import backgroundImage from '../images/background-menu.jpg'
import React from 'react';
import Button from "../components/Button";
import Title from "../components/Title";
import InputRange from "../components/InputRange";
import InputRadio from "../components/InputRadio";

export default function Home() {
  const data = ['2', '3', '4', '5'];
  const data1 = ['A', '9', '19', '50', '99', '999'];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={css`
        background-image: url(${backgroundImage.src});
        background-repeat: no-repeat;
        background-size: cover;
        width: 100%;
        min-height: 100vh;
        display: grid;
        place-items: center;
      `}>
        <div className={css`
          background: linear-gradient(198.7deg, #7F75F0 -40.02%, #101F32 96.22%);
          border-radius: 20px;
          padding: 20px;
        `}>
          <form className={css`
            background: #FFFFFF;
            border-radius: 20px;
            padding: 37px 64px 29px 64px;
            display: flex;
            flex-direction: column;
            align-items: center;
          `}>
            <div className={css`width: 366px; margin-bottom: 53px;`}><InputRange id={'subject'} data={data} label={'Кол-во предметов'} min={2} max={5}/></div>

            <div className={css`width: 531px; margin-bottom: 53px;`}><InputRange id={'importance'} data={data1} label={'Значения'} min={1} max={6}/></div>

            <div className={css`display: flex; gap: 36px; width: 100%; margin-bottom: 92px;`}>
              <InputRadio id={'radio-1'} value={"1"} label={'По возрастанию'}/>
              <InputRadio id={'radio-2'} value={"2"} label={'По убыванию'}/>
            </div>
            <Button>Играть</Button>
          </form>
        </div>
      </main>
    </>
  )
}

